### ISSUE TITLE
Bridge for 6 & 8 lane median roads is not drawn correctly after Sunset Harbor

### ISSUE THREAD

**Issue by CMircea** [andreharv/NetworkExtensions#19]
This is what the bridge looks like when drawn:

![](https://i.imgur.com/DOxPoak.png)

See also issue #16, although it's worse now.

**Comment by drok** [comment]
Fixed in drok@2887084

**Comment by CMircea** [comment]
Great, nobody cares. It's already fixed in NExt 2 since the 6 April 2020 update, on the workshop.
