### ISSUE TITLE
does not work outside steam?

### ISSUE THREAD

**Issue by boeljoet** [andreharv/NetworkExtensions#22]
i tryed this mod when epic games made CS free

but no roads show up

related topics
https://steamcommunity.com/app/255710/discussions/0/1743343017631693843/
https://www.reddit.com/r/CitiesSkylinesModding/comments/6fu1vv/network_extensions_2_roads_not_showing/

altrough these posts are old, they are the most update ones

**Comment by boeljoet** [comment]
ok, it does work but,
in your mod folder cal the folder with the mod "Network Extensions 2" - and nothing else
 if you download it from steam the folder name is 812125426

**Comment by drok** [comment]
This issue is also fixed in drok@2887084 which allows local install in any folder, included first in v1.0.2
