### ISSUE TITLE
The game crashes to the desktop when I put the road from the modification Network Extensions 2

### ISSUE THREAD

**Issue by Robin91862** [andreharv/NetworkExtensions#31]
[2023-03-12_135642.zip](https://github.com/andreharv/NetworkExtensions/files/10950868/2023-03-12_135642.zip)
I'm using **Epic Games** version of Cities: Skylines
Windows 11 Home
AMD Ryzen 5 3550H
NVIDIA GeForce GTX 1650
16 GB RAM

**Comment by Robin91862** [comment]
*16 GB RAM

**Comment by LoboThExile** [comment]
try disabling unifiedui
